<?php
use UnifiedUI\Module as UI;

/* @var $ui \UnifiedUI\Module */
$ui = $this->app->unifiedUI();

/* @var $request \Request\Module */
$request = $this->app->request();
?>
<!DOCTYPE html>
<html ng-app="bliss" ng-controller="bliss.AppCtrl">
	<head>
		<base href="<?=BASE_URL?>">
		<meta charset="utf-8">
		<meta name="fragment" content="!">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
		<meta name="mobile-web-app-capable" content="yes">
		
		<title ng-bind="app.name"></title>
		
		<link rel="import" href="./polymer/bower_components/polymer/polymer.html">
		<link rel="import" href="./polymer/bower_components/core-icons/core-icons.html">
		<link rel="import" href="./polymer/bower_components/core-icons/social-icons.html">
		<link rel="import" href="./polymer/bower_components/paper-icon-button/paper-icon-button.html">
		
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:500,300,700,400">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="./assets/all.css">
	</head>
	<body ng-controller="unifiedUI.LayoutCtrl">
		<header id="header" class="shadow">
			<paper-icon-button icon="menu" class="menuToggle" ng-click="toggleMenu()" ng-class="{active:menuOpen}"></paper-icon-button>
			
			<aside class="widgets">
				<?=$ui->renderInjectables(UI::AREA_HEADER_WIDGETS)?>
			</aside>
			
			<h1>
				<a href="./" ng-bind="app.name"></a>
			</h1>
		</header>
		
		<nav id="menu" class="shadow" ng-class="{open:menuOpen}">
			<?=$ui->renderInjectables(UI::AREA_MENU)?>
		</nav>
		<div id="menuOverlay" ng-click="toggleMenu()" ng-class="{visible:menuOpen}"></div>
		
		<div id="pageError" class="alert alert-danger shadow" ng-class="{visible:pageError}">
			<paper-icon-button icon="close" ng-click="clearPageError()"></paper-icon-button>
			<p>
				{{pageError.message}}
				&nbsp;
			</p>
		</div>
		
		<div id="content">
			<div ng-view></div>
		</div>
		
		<script type="text/ng-template" id="./<?=$request->uri()?>"><?=$this->contents()?></script>
		
		<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular-route.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular-resource.min.js"></script>
		<script src="./assets/all.js"></script>
	</body>
</html>